# Generated by Django 3.2 on 2021-04-18 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('President', models.CharField(blank=True, max_length=50)),
                ('Secretary', models.CharField(blank=True, max_length=50)),
                ('Organizer', models.CharField(blank=True, max_length=50)),
                ('Treasurer', models.CharField(blank=True, max_length=50)),
                ('ExchangeOfficer', models.CharField(blank=True, max_length=50)),
                ('HealthOfficer', models.CharField(blank=True, max_length=50)),
                ('VicePresident', models.CharField(blank=True, max_length=50)),
                ('Pro', models.CharField(blank=True, max_length=50)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('FirstName', models.CharField(blank=True, max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50)),
                ('Gender', models.TextField(choices=[('m', 'Male'), ('f', 'Female')], default='male', max_length=6)),
                ('Reg_No', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.CharField(choices=[('pbl1', 'pbl1'), ('pbl1B', 'pbl1B'), ('pbl2', 'pbl2'), ('pbl3', 'pbl3'), ('pbl3B', 'pbl3B'), ('pbl4', 'pbl4'), ('pbl5', 'pbl5'), ('pbl6', 'pbl6')], max_length=5)),
                ('profilePic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.category')),
            ],
        ),
    ]
