# Generated by Django 3.2 on 2021-04-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_candidate_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profilePic',
            field=models.ImageField(blank=True, default='profile_pics/candidate.png', null=True, upload_to='profile_pics'),
        ),
    ]
